name: Shirshak Actions Demo
on: 
 workflow_dispatch: {}

jobs:
  build-and-run:
     runs-on: ubuntu-latest

     steps:
       - name: Check out repository code
         uses: actions/checkout@v4
       
       - name: List all directories
         run: ls -a
       
       - name: List all directories
         run: |
           cd directory1
           ls -a

       - name: List all second directories
         run: |
           cd directory2
           ls -a

       - name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
           distribution: 'temurin' 
           java-version: '17'

       - name: Compile Java File
         run: javac HelloWorld.java

       - name: Run Java Program
         run: java HelloWorld
